# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Lifecycle' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'

  # Pods for Lifecycle

  target 'LifecycleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LifecycleUITests' do
    # Pods for testing
  end

end
